CREATE TABLE JSON_TRACKING (
  JSON_TRACKING_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  JSON_ID VARCHAR(64) NOT NULL,
  BASE64_ENCODED_JSON VARCHAR(255) NULL, -- Up to 255
  SIDE VARCHAR(32) NOT NULL,
  CREATED_DATE DATE NOT NULL,
  UPDATED_DATE DATE NULL
);



